// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Request 1",
    id: "5e2eed40-cb2a-4626-9f2e-6f074c2b0998",
    method: "GET",
    address: "{{baseUrl}}/ping",
    post(response) {
      pm.test("Ping responde correctamente", function() {
        pm.expect([200, 201]).to.include(pm.response.code);
      });
    }
  });

  postman[Request]({
    name: "Request 2",
    id: "3493f4fa-a4fc-4c66-901d-6b6b331a0cea",
    method: "POST",
    address: "{{baseUrl}}/auth",
    data:
      '{\r\n  "username": "{{username}}",\r\n  "password": "{{password}}"\r\n}',
    post(response) {
      pm.test("Auth devuelve token", function() {
        pm.expect(pm.response.code).to.be.oneOf([200, 201]);
        const jsonData = pm.response.json();
        pm.expect(jsonData).to.have.property("token");
        pm.environment.set("token", jsonData.token);
      });
    }
  });

  postman[Request]({
    name: "Request 3",
    id: "389465cc-02e6-45c8-b1fb-064193553114",
    method: "POST",
    address: "{{baseUrl}}/booking",
    data:
      '{\r\n  "firstname": "Luis",\r\n  "lastname": "Prueba",\r\n  "totalprice": 150,\r\n  "depositpaid": true,\r\n  "bookingdates": {\r\n    "checkin": "2026-04-10",\r\n    "checkout": "2026-04-15"\r\n  },\r\n  "additionalneeds": "Breakfast"\r\n}',
    post(response) {
      pm.test("Create booking devuelve id", function() {
        pm.expect(pm.response.code).to.be.oneOf([200, 201]);
        const jsonData = pm.response.json();
        pm.expect(jsonData).to.have.property("bookingid");
        pm.environment.set("bookingId", jsonData.bookingid);
      });
    }
  });

  postman[Request]({
    name: "Request 4",
    id: "428655c0-ea6f-4748-968f-f85194f8e1a7",
    method: "GET",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    post(response) {
      pm.test("Get booking recupera la reserva creada", function() {
        pm.expect(pm.response.code).to.equal(200);
        const jsonData = pm.response.json();
        pm.expect(jsonData.firstname).to.eql("Luis");
        pm.expect(jsonData.lastname).to.eql("Prueba");
      });
    }
  });

  postman[Request]({
    name: "Request 5",
    id: "cecbaa65-3d52-4b66-b0d4-0c8638ff39bd",
    method: "PATCH",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    data:
      '{\r\n  "firstname": "Anibal",\r\n  "additionalneeds": "Breakfast and dinner"\r\n}',
    headers: {
      Cookie: "token={{token}}"
    },
    post(response) {
      pm.test("Patch booking actualiza campos", function() {
        pm.expect([200, 201]).to.include(pm.response.code);
        const jsonData = pm.response.json();
        pm.expect(jsonData.firstname).to.eql("Anibal");
      });
    }
  });

  postman[Request]({
    name: "Request 6",
    id: "a27975a0-1fd0-4574-b6ad-9f5a75b4b32b",
    method: "GET",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    post(response) {
      pm.test("La reserva refleja los cambios", function() {
        pm.expect(pm.response.code).to.equal(200);
        const jsonData = pm.response.json();
        pm.expect(jsonData.firstname).to.eql("Anibal");
        pm.expect(jsonData.additionalneeds).to.eql("Breakfast and dinner");
      });
    }
  });

  postman[Request]({
    name: "Request 7",
    id: "ec897465-1528-4f2f-a662-173662051dcd",
    method: "DELETE",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    headers: {
      Cookie: "token={{token}}"
    },
    post(response) {
      pm.test("Delete booking responde correctamente", function() {
        pm.expect([200, 201, 202, 204]).to.include(pm.response.code);
      });
    }
  });

  postman[Request]({
    name: "Request 8",
    id: "d6bedcaa-567c-4bb6-929c-9b3ef7910811",
    method: "GET",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    post(response) {
      pm.test("La reserva ya no existe o no está disponible", function() {
        pm.expect([404, 405]).to.include(pm.response.code);
      });
    }
  });

  postman[Request]({
    name: "Request 9",
    id: "847749d6-cbf4-4993-9c42-d79a53ad3a92",
    method: "PATCH",
    address: "{{baseUrl}}/booking/{{bookingId}}",
    post(response) {
      pm.test("Sin token la actualización debe fallar", function() {
        pm.expect([401, 403, 405]).to.include(pm.response.code);
      });
    }
  });
}
